package sirket;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class AnaYer extends javax.swing.JFrame {

    /**
     * Creates new form AnaYer
     */
    public AnaYer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jDesktopPaneFormlar = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeMenu = new javax.swing.JTree();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_personel = new javax.swing.JMenu();
        jMenuItemkayıtlar = new javax.swing.JMenuItem();
        jMenuItemliste = new javax.swing.JMenuItem();
        jMenu_çıkış = new javax.swing.JMenu();
        jMenu_ürünler = new javax.swing.JMenu();
        jMenuItem_Kayıt = new javax.swing.JMenuItem();
        jMenuItem_rapor = new javax.swing.JMenuItem();
        jMenu_yardım = new javax.swing.JMenu();
        jMenuItemhakkında = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(120);

        jDesktopPaneFormlar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jDesktopPaneFormlarFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPaneFormlarLayout = new javax.swing.GroupLayout(jDesktopPaneFormlar);
        jDesktopPaneFormlar.setLayout(jDesktopPaneFormlarLayout);
        jDesktopPaneFormlarLayout.setHorizontalGroup(
            jDesktopPaneFormlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );
        jDesktopPaneFormlarLayout.setVerticalGroup(
            jDesktopPaneFormlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jDesktopPaneFormlar);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("AnaSayfa");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("personel");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("kayıtlar");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("liste");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("ürünler");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("kayıt");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("rapor");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("yardım");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("kullanım");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("hakkında");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("çıkış");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTreeMenu.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreeMenu.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeMenuValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTreeMenu);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jMenu_personel.setText("personel");

        jMenuItemkayıtlar.setText("kayıtlar");
        jMenuItemkayıtlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemkayıtlarActionPerformed(evt);
            }
        });
        jMenu_personel.add(jMenuItemkayıtlar);

        jMenuItemliste.setText("liste");
        jMenuItemliste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemlisteActionPerformed(evt);
            }
        });
        jMenu_personel.add(jMenuItemliste);

        jMenuBar1.add(jMenu_personel);

        jMenu_çıkış.setText("ÇIKIŞ");
        jMenuBar1.add(jMenu_çıkış);

        jMenu_ürünler.setText("ÜRÜNLER");
        jMenu_ürünler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_ürünlerActionPerformed(evt);
            }
        });

        jMenuItem_Kayıt.setText("Kayıt");
        jMenuItem_Kayıt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_KayıtActionPerformed(evt);
            }
        });
        jMenu_ürünler.add(jMenuItem_Kayıt);

        jMenuItem_rapor.setText("Rapor");
        jMenuItem_rapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_raporActionPerformed(evt);
            }
        });
        jMenu_ürünler.add(jMenuItem_rapor);

        jMenuBar1.add(jMenu_ürünler);

        jMenu_yardım.setText("YARDIM");
        jMenu_yardım.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_yardımActionPerformed(evt);
            }
        });

        jMenuItemhakkında.setText("hakkında");
        jMenuItemhakkında.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemhakkındaActionPerformed(evt);
            }
        });
        jMenu_yardım.add(jMenuItemhakkında);

        jMenuBar1.add(jMenu_yardım);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemlisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemlisteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemlisteActionPerformed

    private void jMenuItemkayıtlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemkayıtlarActionPerformed
        personelform frmPersonel = new personelform (); 
        this.jDesktopPaneFormlar.add (frmPersonel); 
        frmPersonel.show();
        
        
    }//GEN-LAST:event_jMenuItemkayıtlarActionPerformed

    private void jTreeMenuValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeMenuValueChanged
       
        String secilen = jTreeMenu.getLastSelectedPathComponent().toString();
        System.out.println("seçilen yol : " + secilen);
        switch(secilen){ 
                
                case "kayıtlar": 
                    personelform frmPersonel = new personelform();
                    this.jDesktopPaneFormlar.add(frmPersonel); 
                    frmPersonel.show();
                    break;
                    
                case "kayıt": 
                    
                     urunkayıtform frmurunkayıt = new urunkayıtform ();
                     this.jDesktopPaneFormlar.add(frmurunkayıt); 
                      frmurunkayıt.show();
                    break;
                 
                case "liste": 
                    break;
                    
                case "Rapor":
                       urunraporform frmurunrapor = new urunraporform ();
                     this.jDesktopPaneFormlar.add(frmurunrapor);
                      frmurunrapor.show();
                    break;
                case "çıkış": System.exit(0); break;
                    
                    
                
                
                            
       }
        
        
        
    }//GEN-LAST:event_jTreeMenuValueChanged

    private void jMenu_yardımActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_yardımActionPerformed
     
    }//GEN-LAST:event_jMenu_yardımActionPerformed

    private void jMenuItemhakkındaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemhakkındaActionPerformed
       hakkında frmhakkında = new hakkında();
       this.jDesktopPaneFormlar.add(frmhakkında);
       frmhakkında.show();
       
  
    }//GEN-LAST:event_jMenuItemhakkındaActionPerformed

    private void jMenuItem_KayıtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_KayıtActionPerformed
       urunkayıtform frmurunkayıt = new urunkayıtform ();
       this.jDesktopPaneFormlar.add(frmurunkayıt); 
       frmurunkayıt.show();
       
    }//GEN-LAST:event_jMenuItem_KayıtActionPerformed

    private void jMenu_ürünlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_ürünlerActionPerformed
     
    }//GEN-LAST:event_jMenu_ürünlerActionPerformed

    private void jMenuItem_raporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_raporActionPerformed
       
                     urunraporform frmurunrapor = new urunraporform ();
                     this.jDesktopPaneFormlar.add(frmurunrapor);
                      frmurunrapor.show();
    }//GEN-LAST:event_jMenuItem_raporActionPerformed

    private void jDesktopPaneFormlarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDesktopPaneFormlarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jDesktopPaneFormlarFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("SYSTEM".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaYer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaYer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaYer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaYer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaYer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneFormlar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Kayıt;
    private javax.swing.JMenuItem jMenuItem_rapor;
    private javax.swing.JMenuItem jMenuItemhakkında;
    private javax.swing.JMenuItem jMenuItemkayıtlar;
    private javax.swing.JMenuItem jMenuItemliste;
    private javax.swing.JMenu jMenu_personel;
    private javax.swing.JMenu jMenu_yardım;
    private javax.swing.JMenu jMenu_çıkış;
    private javax.swing.JMenu jMenu_ürünler;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTreeMenu;
    // End of variables declaration//GEN-END:variables
}
