package sirket;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class urunkayıtform extends javax.swing.JInternalFrame {

    /**
     * Creates new form urunkayıtform
     */
    public urunkayıtform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_AD = new javax.swing.JLabel();
        jTextField_AD = new javax.swing.JTextField();
        jLabel_tanım = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_tanım = new javax.swing.JTextArea();
        jLabel_resim = new javax.swing.JLabel();
        jButton_kaydet = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ürün kayıt formu");

        jLabel_AD.setText("AD");

        jLabel_tanım.setText("TANIM");

        jTextArea_tanım.setColumns(20);
        jTextArea_tanım.setRows(5);
        jScrollPane1.setViewportView(jTextArea_tanım);

        jLabel_resim.setForeground(new java.awt.Color(0, 204, 204));
        jLabel_resim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_resim.setText("ürün resimi yüklemek için tıklayınız");
        jLabel_resim.setOpaque(true);
        jLabel_resim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_resimMouseClicked(evt);
            }
        });

        jButton_kaydet.setText("KAYDET");
        jButton_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_kaydetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_tanım, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_resim, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_AD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_AD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_tanım, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_resim, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton_kaydet)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private String resimAd, resimAdres;
    private File dosya;
    private void jLabel_resimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_resimMouseClicked
        
                JFileChooser resimSecici = new JFileChooser();
                int secim = resimSecici.showOpenDialog(this);
                if (secim== JFileChooser.APPROVE_OPTION){
                    
                    dosya = resimSecici.getSelectedFile();
                    resimAd = dosya.getName(); 
                    resimAdres = dosya.getPath(); 
                    ImageIcon resim = new ImageIcon(resimAdres);
                    jLabel_resim.setIcon(resim);
                    System.out.println("resim adı : " + resimAd + "Resim Adres "+ resimAdres);
                    jLabel_resim.setText(resimAd);
                    
                    
                    
                }
        
        
                
    }//GEN-LAST:event_jLabel_resimMouseClicked

    private void jButton_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_kaydetActionPerformed
      
        String adres = "jdbc:derby://localhost:1527/PERSONEL";
        String kullanıcı = "efe";
        String sifre = "123"; 
        String AD = jTextField_AD.getText();
        String tanım = jTextArea_tanım.getText();
        String sorgu = "INSERT INTO urun (ad,tanim,resimad,resim)" + 
                        "VALUES (?, ?, ?, ?)";
        
        try {
            Connection bag = DriverManager.getConnection(adres, kullanıcı, sifre);
            FileInputStream fis = new FileInputStream(dosya);
            PreparedStatement ps = bag.prepareStatement(sorgu); 
            ps.setString(1, AD);
            ps.setString(2, tanım);
            ps.setString(3, resimAd);
            ps.setBinaryStream(4, fis, (int)dosya.length());
            ps.executeUpdate();
            ps.close(); fis.close(); bag.close();
            
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Kayıt yapılmadı. " + ex.toString());
        } catch (FileNotFoundException ex) {
          JOptionPane.showMessageDialog(null, "Kayıt yapılmadı. " + ex.toString());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Kayıt yapılmadı. " + ex.toString());
        }
        
        
        
        
    }//GEN-LAST:event_jButton_kaydetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_kaydet;
    private javax.swing.JLabel jLabel_AD;
    private javax.swing.JLabel jLabel_resim;
    private javax.swing.JLabel jLabel_tanım;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_tanım;
    private javax.swing.JTextField jTextField_AD;
    // End of variables declaration//GEN-END:variables
}
